import type { Messages } from "./en";

export const ar: Messages = {
  "brand.name":"DOONGDOONG","common.skip":"الانتقال إلى المحتوى الرئيسي","common.home":"العودة إلى شاطئ DOONGDOONG","common.cancel":"إلغاء","common.continue":"متابعة","common.back":"رجوع","common.retry":"إعادة المحاولة","common.optional":"اختياري","common.on":"تشغيل","common.off":"إيقاف","common.settings":"الإعدادات","fatal.title":"تعذّر فتح البحر.","fatal.load":"تعذّر تجهيز البحر. حاول مجددًا بعد قليل.","fatal.reload":"الفتح مجددًا","loading.sea":"نستدعي البحر…",
  "onboarding.selectTitle":"اختر بلدك أو منطقتك ولغتك","onboarding.selectDescription":"يحدّد البلد أو المنطقة نقطة انطلاق الزجاجات، وتحدّد اللغة واجهة التطبيق وترجمة الرسائل المستلمة.","onboarding.language":"اللغة","onboarding.country":"البلد أو المنطقة","onboarding.eyebrow":"تطفو إلى مكان ما في العالم.","onboarding.title":"أرسلها بلا اسم، ودعها تختفي بهدوء.","onboarding.principles":"كيف يعمل DOONGDOONG","onboarding.rule1":"لا ردود ولا إعجابات ولا إشعارات قراءة","onboarding.rule2":"لا يمكن مراجعة الزجاجة أو استعادتها بعد إرسالها","onboarding.rule3":"يمكن الاحتفاظ بالزجاجات المستلمة لمدة 30 يومًا فقط","onboarding.signature":"التوقيع الافتراضي للرسالة","onboarding.signaturePlaceholder":"مثال: مسافر في الليل","onboarding.consent":"أفهم أنه يجب ألا أكتب معلومات شخصية وأن المستلم قد يحفظ الشاشة.","onboarding.starting":"جارٍ البدء…","onboarding.start":"ابدأ","onboarding.error":"تعذّر البدء. حاول مجددًا بعد قليل.",
  "home.shore":"شاطئ DOONGDOONG","home.write":"اكتب رسالة","home.writingRest":"نجهّز الورقة والزجاجة التاليتين…","home.heldBottle":"عرض الزجاجة التي التقطتها","home.pickBottle":"التقاط الزجاجة عند الماء","home.seagull":"الاستماع إلى النورس","home.waiting":"بانتظار أخبار جديدة…","home.keptCount":"عرض الرسائل المحفوظة: {count}","home.guide":"عرض الدليل وإرشادات السلامة","home.available":"هناك زجاجة يمكن التقاطها عند الماء.","home.unavailable":"لا توجد زجاجات عند الماء الآن.",
  "write.lengthError":"اكتب بين 10 و1,000 حرف.","write.blockedPersonal":"لا يمكن أن تتضمن الزجاجة بيانات اتصال أو حسابات أو معلومات تكشف هويتك.","write.blockedCrisis":"لا يمكن إرسال هذه الرسالة الآن. إذا كان حمل الأمر وحدك صعبًا، فتحدث الآن إلى شخص قريب أو مختص.","write.blockedSensitive":"لطّف العبارة قليلًا ليتمكن الجميع من قراءتها بأمان.","write.blockedSpam":"لا يمكن إرسال نص مكرر أو ترويجي إلى البحر.","write.blockedGeneric":"لا يمكن إرسال هذه الرسالة. راجع محتواها.","write.sendError":"تعذّر إطلاق الزجاجة. حاول مجددًا.","write.dailyUsed":"استخدمت كل رسائل اليوم.","write.launching":"تطفو الزجاجة إلى عرض البحر.","write.heading":"اكتب رسالة وضعها في زجاجة","write.crisisHelp":"إذا كنت في خطر فوري، فاطلب المساعدة الآن من شخص قريب أو من خدمة الطوارئ المحلية.","write.form":"رسالة للزجاجة","write.body":"الرسالة","write.placeholder":"إلى شخص لم أقابله من قبل…","write.today":"تاريخ اليوم","write.signature":"التوقيع (اختياري)","write.sea":"البحر الذي ستُطلق إليه","write.guardrail":"لا معلومات شخصية · لا يمكن الاسترجاع بعد الإرسال","write.checking":"جارٍ التحقق من سلامة الرسالة","write.launch":"وضع الرسالة في الزجاجة وإطلاقها","write.packing":"جارٍ وضع الرسالة في الزجاجة.","write.confirmTitle":"هل تريد إطلاق هذه الزجاجة؟","write.confirmDescription":"لا يمكن تعديل الزجاجة بعد إطلاقها. هل تريد الإرسال؟","write.send":"إرسال",
  "catch.openError":"تعذّر فتح الزجاجة.","catch.resolveError":"تعذّر التعامل مع الزجاجة.","catch.heading":"افتح الزجاجة التي وجدتها","catch.open":"فتح الزجاجة وإخراج الرسالة","catch.untouched":"دعها تتابع بلا فتح","catch.opening":"جارٍ فتح الزجاجة.","catch.received":"الرسالة المستلمة","catch.origin":"أُرسلت من {country}","catch.translated":"مترجمة عن {language}","catch.actions":"إجراءات الرسالة المستلمة","catch.redrift":"دعها تتابع","catch.keep":"احتفاظ","catch.report":"إبلاغ","catch.reportConfirm":"تأكيد الإبلاغ","catch.reportWarning":"يؤدي الإبلاغ إلى اختفاء هذه الزجاجة فورًا.",
  "kept.title":"الذكريات","kept.description":"تختفي الزجاجات المحفوظة بعد 30 يومًا.","kept.emptyStamp":"فارغ","kept.empty":"لا توجد زجاجات محفوظة بجانبك.","kept.home":"العودة إلى الشاطئ","kept.discard":"تخلّص منها","kept.confirm":"تأكيد إجراء الزجاجة المحفوظة","kept.discardWarning":"عند التخلص منها، تختفي الرسالة الآن.","time.now":"الآن","time.minutes":"بعد {minutes} د","time.hours":"بعد {hours} س","time.hoursMinutes":"بعد {hours} س و{minutes} د","time.tomorrow":"تختفي غدًا","time.days":"تختفي بعد {days} أيام",
  "guide.eyebrow":"الدليل","guide.title":"وعد DOONGDOONG","guide.oneTitle":"زجاجة واحدة، شخص واحد","guide.oneBody":"بعد القراءة، أرسلها إلى الشخص التالي.","guide.blindTitle":"مجهولة تمامًا","guide.blindBody":"لا أحد يعرف الكاتب أو القارئ أو المسار.","guide.noReplyTitle":"لقاء بلا ردود","guide.noReplyBody":"لا ردود ولا إعجابات ولا إشعارات قراءة.","guide.goneTitle":"ستختفي يومًا ما","guide.goneBody":"تخلّص منها الآن أو احتفظ بها حتى 30 يومًا.","guide.safetyEyebrow":"من أجل بحر أكثر أمانًا","guide.safetyTitle":"لا تكتب ما يكشف هويتك.","guide.safety1":"لا تذكر الاسم الحقيقي أو الهاتف أو البريد أو حسابات التواصل أو العنوان أو المدرسة.","guide.safety2":"لا يُسمح بالمحتوى الجنسي أو الكراهية أو التهديد أو تفاصيل الجرائم أو إيذاء النفس أو الإعلانات.","guide.safety3":"أبلغ عن أي زجاجة مزعجة أو خطرة من شاشة القراءة.","guide.safety4":"لا تستطيع التقنية منع تصرفات المستلم مثل لقطات الشاشة.",
  "settings.title":"الإعدادات","settings.profileTitle":"البلد أو المنطقة واللغة","settings.profileDescription":"يحدّد البلد أو المنطقة انطلاق الزجاجات الجديدة، وتحدّد اللغة التطبيق والترجمات.","settings.saveProfile":"حفظ البلد واللغة","settings.profileSaved":"تم حفظ البلد واللغة.","settings.profileError":"تعذّر حفظ البلد واللغة.","settings.writingTitle":"إعدادات الرسالة الافتراضية","settings.writingDescription":"اختر ما يُملأ عند فتح رسالة جديدة.","settings.signature":"التوقيع الافتراضي","settings.signatureError":"تعذّر حفظ التوقيع الافتراضي.","settings.date":"إضافة تاريخ اليوم تلقائيًا","settings.motion":"تقليل الحركة","country.unknown":"مكان غير معروف","country.other":"بلد أو منطقة أخرى","sea.pacific":"المحيط الهادئ","sea.atlantic":"المحيط الأطلسي","sea.indian":"المحيط الهندي","sea.arctic":"المحيط المتجمد الشمالي","sea.southern":"المحيط الجنوبي"
};
