import type { Messages } from "./en";
import { pwaMessages } from "./pwa";

export const hi: Messages = {
  ...pwaMessages.hi,
  "settings.socialTitle":"जुड़े हुए खाते","settings.socialDescription":"DOONGDOONG से जुड़े लॉगिन खाते देखें या कोई दूसरा खाता जोड़ें।","settings.socialConnected":"जुड़ा हुआ","settings.socialConnect":"जोड़ें","settings.socialConnecting":"जोड़ा जा रहा है…","settings.socialNotice":"जुड़े खाते केवल लॉगिन के लिए उपयोग होते हैं। आपके पत्र गुमनाम रहते हैं।","settings.socialError":"यह खाता नहीं जोड़ा जा सका। खाता जाँचकर फिर कोशिश करें।",
  "brand.name":"DOONGDOONG","common.skip":"मुख्य सामग्री पर जाएँ","common.home":"DOONGDOONG तट पर लौटें","common.cancel":"रद्द करें","common.continue":"आगे बढ़ें","common.back":"वापस","common.retry":"फिर कोशिश करें","common.optional":"वैकल्पिक","common.on":"चालू","common.off":"बंद","common.settings":"सेटिंग्स","fatal.title":"समुद्र नहीं खुल सका।","fatal.load":"समुद्र तैयार नहीं हो सका। थोड़ी देर बाद फिर कोशिश करें।","fatal.reload":"फिर खोलें","loading.sea":"समुद्र को बुलाया जा रहा है…",
  "auth.eyebrow":"बिना नाम की एक शांत मुलाकात","auth.title":"समुद्र खोलने के लिए साइन इन करें","auth.description":"एक खाता चुनें। आपकी लॉगिन जानकारी पत्रों या पाने वालों को कभी नहीं दिखाई जाती।","auth.providers":"सोशल लॉगिन विकल्प","auth.google":"Google से जारी रखें","auth.apple":"Apple से जारी रखें","auth.naver":"NAVER से जारी रखें","auth.redirecting":"लॉगिन खोला जा रहा है…","auth.notice":"खाता केवल लॉगिन और सेवा सुरक्षा के लिए उपयोग होता है। यह पत्रों में कभी नहीं दिखता।","auth.session":"लॉगिन की जाँच हो रही है…","auth.error":"साइन इन नहीं हो सका। फिर कोशिश करें।",
  "onboarding.selectTitle":"अपना देश या क्षेत्र और भाषा चुनें","onboarding.selectDescription":"देश या क्षेत्र बोतल का आरंभ बताता है। भाषा ऐप और मिले पत्रों के अनुवाद को नियंत्रित करती है।","onboarding.language":"भाषा","onboarding.country":"देश या क्षेत्र","onboarding.eyebrow":"दुनिया में कहीं बहते हुए।","onboarding.title":"बिना नाम भेजें और उसे चुपचाप मिट जाने दें।","onboarding.principles":"DOONGDOONG कैसे काम करता है","onboarding.rule1":"कोई जवाब, लाइक या पढ़े जाने की सूचना नहीं","onboarding.rule2":"भेजी हुई बोतल को देखा या वापस नहीं लिया जा सकता","onboarding.rule3":"मिली बोतल केवल 30 दिन रखी जा सकती है","onboarding.signature":"पत्र का डिफ़ॉल्ट हस्ताक्षर","onboarding.signaturePlaceholder":"जैसे: रात का एक यात्री","onboarding.consent":"मैं समझता/समझती हूँ कि निजी जानकारी नहीं लिखनी है और पाने वाला स्क्रीन सहेज सकता है।","onboarding.starting":"शुरू हो रहा है…","onboarding.start":"शुरू करें","onboarding.error":"शुरू नहीं हो सका। थोड़ी देर बाद फिर कोशिश करें।",
  "home.shore":"DOONGDOONG तट","home.write":"पत्र लिखें","home.writingRest":"अगला कागज़ और बोतल तैयार हो रहे हैं…","home.heldBottle":"उठाई हुई बोतल देखें","home.pickBottle":"पानी के पास की बोतल उठाएँ","home.seagull":"समुद्री पक्षी की आवाज़ सुनें","home.waiting":"नई खबर की प्रतीक्षा…","home.keptCount":"सहेजे गए {count} पत्र देखें","home.guide":"मार्गदर्शिका और सुरक्षा निर्देश देखें","home.available":"पानी के पास उठाने के लिए एक बोतल है।","home.unavailable":"अभी पानी के पास कोई बोतल नहीं है।",
  "write.lengthError":"10 से 1,000 अक्षरों के बीच लिखें।","write.blockedPersonal":"बोतल में संपर्क, खाते या पहचान बताने वाली जानकारी नहीं हो सकती।","write.blockedCrisis":"यह पत्र अभी नहीं भेजा जा सकता। अगर अकेले सहना कठिन है, तो अभी किसी करीबी या विशेषज्ञ से बात करें।","write.blockedSensitive":"शब्दों को थोड़ा नरम करें ताकि हर कोई सुरक्षित रूप से पढ़ सके।","write.blockedSpam":"दोहराई हुई या प्रचार सामग्री समुद्र में नहीं भेजी जा सकती।","write.blockedGeneric":"यह पत्र नहीं भेजा जा सकता। सामग्री जाँचें।","write.sendError":"बोतल नहीं भेजी जा सकी। फिर कोशिश करें।","write.dailyUsed":"आज के सभी पत्र इस्तेमाल हो चुके हैं।","write.launching":"बोतल समुद्र की ओर बह रही है।","write.heading":"पत्र लिखकर बोतल में रखें","write.crisisHelp":"अगर आप तुरंत खतरे में हैं, तो अभी पास के किसी व्यक्ति या स्थानीय आपात सेवा से मदद लें।","write.form":"बोतल के लिए पत्र","write.body":"पत्र","write.placeholder":"किसी ऐसे व्यक्ति के लिए जिससे मैं कभी नहीं मिला…","write.today":"आज की तारीख","write.signature":"हस्ताक्षर (वैकल्पिक)","write.sea":"जिस समुद्र में भेजना है","write.guardrail":"निजी जानकारी नहीं · भेजने के बाद वापस नहीं","write.checking":"पत्र की सुरक्षा जाँची जा रही है","write.launch":"पत्र को बोतल में रखकर भेजें","write.packing":"पत्र बोतल में रखा जा रहा है।","write.confirmTitle":"यह बोतल भेजें?","write.confirmDescription":"भेजी हुई बोतल बदली नहीं जा सकती। भेजें?","write.send":"भेजें",
  "catch.openError":"बोतल नहीं खुल सकी।","catch.resolveError":"बोतल पर कार्रवाई नहीं हो सकी।","catch.heading":"मिली हुई बोतल खोलें","catch.open":"बोतल खोलकर पत्र निकालें","catch.untouched":"बिना खोले आगे भेजें","catch.opening":"बोतल खुल रही है।","catch.received":"मिला हुआ पत्र","catch.origin":"{country} से भेजा गया","catch.translated":"{language} से अनुवादित","catch.actions":"मिले हुए पत्र की कार्रवाइयाँ","catch.redrift":"आगे भेजें","catch.keep":"सहेजें","catch.report":"रिपोर्ट करें","catch.reportConfirm":"रिपोर्ट की पुष्टि","catch.reportWarning":"रिपोर्ट करने पर यह बोतल तुरंत गायब हो जाएगी।",
  "kept.title":"सहेजी यादें","kept.description":"सहेजी गई बोतलें 30 दिन बाद गायब हो जाती हैं।","kept.emptyStamp":"खाली","kept.empty":"आपके पास अभी कोई सहेजी हुई बोतल नहीं है।","kept.home":"तट पर लौटें","kept.discard":"फेंकें","kept.confirm":"सहेजी बोतल की कार्रवाई की पुष्टि","kept.discardWarning":"फेंकने पर यह पत्र अभी गायब हो जाएगा।","time.now":"अभी","time.minutes":"{minutes} मिनट में","time.hours":"{hours} घंटे में","time.hoursMinutes":"{hours} घंटे {minutes} मिनट में","time.tomorrow":"कल गायब होगा","time.days":"{days} दिन में गायब होगा",
  "guide.eyebrow":"मार्गदर्शिका","guide.title":"DOONGDOONG का वादा","guide.oneTitle":"एक बोतल, एक व्यक्ति","guide.oneBody":"पढ़ने के बाद इसे अगले व्यक्ति को भेजें।","guide.blindTitle":"पूरी तरह गुमनाम","guide.blindBody":"लेखक, पाठक या रास्ते की पहचान नहीं होती।","guide.noReplyTitle":"बिना जवाब की मुलाकात","guide.noReplyBody":"कोई जवाब, लाइक या पढ़े जाने की सूचना नहीं।","guide.goneTitle":"एक दिन गायब","guide.goneBody":"अभी फेंकें या 30 दिन तक सहेजें।","guide.safetyEyebrow":"सुरक्षित समुद्र के लिए","guide.safetyTitle":"ऐसा कुछ न लिखें जिससे आपकी पहचान हो।","guide.safety1":"असली नाम, फोन, ईमेल, सोशल अकाउंट, पता या स्कूल न लिखें।","guide.safety2":"यौन सामग्री, नफ़रत, धमकी, अपराध या खुद को नुकसान पहुँचाने का विवरण और विज्ञापन नहीं भेजे जा सकते।","guide.safety3":"परेशान करने वाली या खतरनाक बोतल को पढ़ने की स्क्रीन से रिपोर्ट करें।","guide.safety4":"तकनीक पाने वाले को स्क्रीनशॉट लेने से नहीं रोक सकती।",
  "settings.title":"सेटिंग्स","settings.profileTitle":"देश या क्षेत्र और भाषा","settings.profileDescription":"देश या क्षेत्र नई बोतलों का आरंभ बताता है। भाषा ऐप और अनुवाद नियंत्रित करती है।","settings.saveProfile":"देश और भाषा सहेजें","settings.profileSaved":"देश और भाषा सहेजे गए।","settings.profileError":"देश और भाषा नहीं सहेजे जा सके।","settings.writingTitle":"पत्र के डिफ़ॉल्ट","settings.writingDescription":"नया पत्र खोलने पर अपने-आप भरने वाली चीज़ें चुनें।","settings.signature":"डिफ़ॉल्ट हस्ताक्षर","settings.signatureError":"डिफ़ॉल्ट हस्ताक्षर नहीं सहेजा जा सका।","settings.date":"आज की तारीख अपने-आप जोड़ें","settings.motion":"गतिविधि कम करें","settings.accountTitle":"खाता","settings.accountDescription":"इस डिवाइस पर DOONGDOONG से साइन आउट करें।","settings.signOut":"साइन आउट","settings.signingOut":"साइन आउट हो रहा है…","settings.signOutError":"साइन आउट नहीं हो सका। फिर कोशिश करें।","country.unknown":"अज्ञात स्थान","country.other":"अन्य देश या क्षेत्र","sea.pacific":"प्रशांत महासागर","sea.atlantic":"अटलांटिक महासागर","sea.indian":"हिंद महासागर","sea.arctic":"आर्कटिक महासागर","sea.southern":"दक्षिणी महासागर"
};
