import type { Messages } from "./en";
import { pwaMessages } from "./pwa";

export const ja: Messages = {
  ...pwaMessages.ja,
  "settings.socialTitle":"ソーシャルログイン連携","settings.socialDescription":"DOONGDOONGに連携済みのログインアカウントを確認したり、別のアカウントを追加できます。","settings.socialConnected":"連携済み","settings.socialConnect":"連携する","settings.socialConnecting":"連携中…","settings.socialNotice":"連携したアカウントはログインにのみ使用し、手紙には表示しません。","settings.socialError":"アカウントを連携できませんでした。アカウントを確認してもう一度お試しください。",
  "brand.name":"DOONGDOONG","common.skip":"本文へスキップ","common.home":"DOONGDOONGの浜辺に戻る","common.cancel":"キャンセル","common.continue":"次へ","common.back":"戻る","common.retry":"もう一度試す","common.optional":"任意","common.on":"オン","common.off":"オフ","common.settings":"設定",
  "fatal.title":"海を開けませんでした。","fatal.load":"海のデータを準備できませんでした。しばらくしてからもう一度お試しください。","fatal.reload":"もう一度開く","loading.sea":"海を呼び寄せています…",
  "auth.eyebrow":"名前のない静かな出会い","auth.title":"ログインして海を開いてください","auth.description":"アカウントを一つ選んでください。ログイン情報が手紙や受信者に表示されることはありません。","auth.providers":"ソーシャルログインの選択肢","auth.google":"Googleで続ける","auth.apple":"Appleで続ける","auth.naver":"NAVERで続ける","auth.redirecting":"ログイン画面を開いています…","auth.notice":"アカウント情報はログインとサービスの安全のためだけに使用し、手紙には表示しません。","auth.session":"ログイン状態を確認しています…","auth.error":"ログインできませんでした。もう一度お試しください。",
  "onboarding.selectTitle":"国・地域と言語を選んでください","onboarding.selectDescription":"国・地域はボトルの出発地を、言語はアプリの表示と受信した手紙の翻訳基準を決めます。","onboarding.language":"言語","onboarding.country":"国または地域","onboarding.eyebrow":"世界のどこかへ、ゆらゆら。","onboarding.title":"名前を告げずに流し、静かに消えていきます。","onboarding.principles":"DOONGDOONGの使い方","onboarding.rule1":"返信・いいね・既読表示なし","onboarding.rule2":"送った後の確認・回収は不可","onboarding.rule3":"受け取ったボトルの保管は30日まで","onboarding.signature":"手紙の既定の署名","onboarding.signaturePlaceholder":"例：ある夜の旅人","onboarding.consent":"個人情報を書かず、受信者が画面を保存できることを理解しました。","onboarding.starting":"開始しています…","onboarding.start":"始める","onboarding.error":"開始できませんでした。しばらくしてからもう一度お試しください。",
  "home.shore":"DOONGDOONGの浜辺","home.write":"手紙を書く","home.writingRest":"次の便せんとボトルを準備しています…","home.heldBottle":"拾ったボトルを見る","home.pickBottle":"波打ち際のボトルを拾う","home.seagull":"カモメの声を聞く","home.waiting":"新しい知らせを待っています…","home.keptCount":"保管した手紙{count}通を見る","home.guide":"使い方と安全案内を見る","home.available":"波打ち際に拾えるボトルがあります。","home.unavailable":"今、波打ち際にボトルはありません。",
  "write.lengthError":"手紙は10文字以上1,000文字以内で書いてください。","write.blockedPersonal":"連絡先やアカウントなど、個人を特定できる情報は入れられません。","write.blockedCrisis":"この手紙は今は送れません。一人で抱えるのがつらいときは、身近な人や専門家に今すぐ相談してください。","write.blockedSensitive":"誰もが安心して読めるよう、表現を少しやわらげてください。","write.blockedSpam":"繰り返しの文句や宣伝内容は海に流せません。","write.blockedGeneric":"この手紙は送れません。内容を見直してください。","write.sendError":"ボトルを流せませんでした。もう一度お試しください。","write.dailyUsed":"今日送れる手紙をすべて使いました。","write.launching":"ボトルが海へ流れていきます。","write.heading":"手紙を書いてボトルに入れる","write.crisisHelp":"差し迫った危険がある場合は、近くの人または地域の緊急窓口に今すぐ助けを求めてください。","write.form":"ボトルに入れる手紙","write.body":"手紙の内容","write.placeholder":"まだ見ぬ誰かへ…","write.today":"今日の日付","write.signature":"署名（任意）","write.sea":"流す海","write.guardrail":"個人情報禁止・送った後は回収不可","write.checking":"手紙の安全性を確認中","write.launch":"手紙をボトルに入れて海へ流す","write.packing":"手紙をボトルに入れています。","write.confirmTitle":"このボトルを流しますか？","write.confirmDescription":"流したボトルは編集できません。送りますか？","write.send":"送る",
  "catch.openError":"ボトルを開けませんでした。","catch.resolveError":"ボトルを処理できませんでした。","catch.heading":"拾ったボトルを開ける","catch.open":"ボトルを開けて手紙を取り出す","catch.untouched":"開けずにそのまま流す","catch.opening":"ボトルを開けています。","catch.received":"受け取った手紙","catch.origin":"送信元：{country}","catch.translated":"{language}の原文から翻訳","catch.actions":"受け取った手紙の操作","catch.redrift":"もう一度流す","catch.keep":"保管する","catch.report":"報告","catch.reportConfirm":"報告の確認","catch.reportWarning":"報告すると、このボトルはすぐに消えます。",
  "kept.title":"保管箱","kept.description":"保管したボトルは30日後に消えます。","kept.emptyStamp":"空です","kept.empty":"そばに置いたボトルはありません。","kept.home":"浜辺に戻る","kept.discard":"捨てる","kept.confirm":"保管したボトルの操作確認","kept.discardWarning":"捨てると、この手紙は今すぐ消えます。",
  "time.now":"今","time.minutes":"{minutes}分後","time.hours":"{hours}時間後","time.hoursMinutes":"{hours}時間{minutes}分後","time.tomorrow":"明日消えます","time.days":"{days}日後に消えます",
  "guide.eyebrow":"使い方","guide.title":"DOONGDOONGの約束","guide.oneTitle":"一つのボトル、一人の人","guide.oneBody":"読んだ後にもう一度流すと、次の人へ届きます。","guide.blindTitle":"完全な匿名","guide.blindBody":"書いた人、読んだ人、移動経路は分かりません。","guide.noReplyTitle":"返信のない出会い","guide.noReplyBody":"返信・いいね・既読表示はありません。","guide.goneTitle":"いつか消える","guide.goneBody":"捨てればすぐ、保管すれば30日後に消えます。","guide.safetyEyebrow":"安全な海のために","guide.safetyTitle":"自分を特定できる情報は書かないでください。","guide.safety1":"本名、電話番号、メール、SNS、住所、学校は書かないでください。","guide.safety2":"性的表現、差別、脅迫、犯罪・自傷の具体的内容、広告は送れません。","guide.safety3":"不快または危険なボトルは閲覧画面からすぐ報告できます。","guide.safety4":"スクリーンショットなど受信者の行動まで技術的に防ぐことはできません。",
  "settings.title":"設定","settings.profileTitle":"国・地域と言語","settings.profileDescription":"国・地域は新しいボトルの出発地を、言語はアプリ表示と翻訳基準を決めます。","settings.saveProfile":"国・地域と言語を保存","settings.profileSaved":"国・地域と言語を保存しました。","settings.profileError":"国・地域と言語を保存できませんでした。","settings.writingTitle":"手紙の初期設定","settings.writingDescription":"新しい手紙を開いたときに自動入力する内容を決めます。","settings.signature":"既定の署名","settings.signatureError":"既定の署名を保存できませんでした。","settings.date":"今日の日付を自動入力","settings.motion":"動きを減らす","settings.accountTitle":"アカウント","settings.accountDescription":"この端末でDOONGDOONGからログアウトします。","settings.signOut":"ログアウト","settings.signingOut":"ログアウトしています…","settings.signOutError":"ログアウトできませんでした。もう一度お試しください。",
  "country.unknown":"不明な場所","country.other":"その他の国・地域","sea.pacific":"太平洋","sea.atlantic":"大西洋","sea.indian":"インド洋","sea.arctic":"北極海","sea.southern":"南極海"
};
