import type { Messages } from "./en";
import { pwaMessages } from "./pwa";

export const zhHans: Messages = {
  ...pwaMessages["zh-Hans"],
  "settings.socialTitle":"社交登录关联","settings.socialDescription":"查看已关联到 DOONGDOONG 的登录账号，或添加其他账号。","settings.socialConnected":"已关联","settings.socialConnect":"关联","settings.socialConnecting":"正在关联…","settings.socialNotice":"关联账号仅用于登录，不会显示在信件中。","settings.socialError":"无法关联该账号。请检查账号后重试。",
  "brand.name":"DOONGDOONG","common.skip":"跳到主要内容","common.home":"返回DOONGDOONG海滩","common.cancel":"取消","common.continue":"继续","common.back":"返回","common.retry":"重试","common.optional":"选填","common.on":"开","common.off":"关","common.settings":"设置",
  "fatal.title":"无法打开大海。","fatal.load":"无法准备海洋数据，请稍后重试。","fatal.reload":"重新打开","loading.sea":"正在唤来大海…",
  "auth.eyebrow":"一场不问姓名的安静相遇","auth.title":"登录后打开大海","auth.description":"请选择一个账号。登录信息绝不会显示在信件中，也不会展示给收件人。","auth.providers":"社交登录选项","auth.google":"使用 Google 继续","auth.apple":"使用 Apple 继续","auth.naver":"使用 NAVER 继续","auth.redirecting":"正在打开登录页面…","auth.notice":"账号信息仅用于登录和服务安全，不会显示在信件中。","auth.session":"正在检查登录状态…","auth.error":"无法登录，请重试。",
  "onboarding.selectTitle":"请选择国家或地区和语言","onboarding.selectDescription":"国家或地区标记瓶子的出发地，语言决定应用界面和收到信件的翻译。","onboarding.language":"语言","onboarding.country":"国家或地区","onboarding.eyebrow":"漂向世界某处。","onboarding.title":"匿名寄出，然后静静消失。","onboarding.principles":"DOONGDOONG使用规则","onboarding.rule1":"没有回复、点赞或已读回执","onboarding.rule2":"寄出后无法查看或收回","onboarding.rule3":"收到的瓶子最多保存30天","onboarding.signature":"信件默认署名","onboarding.signaturePlaceholder":"例如：夜晚的旅人","onboarding.consent":"我明白不能填写个人信息，收件人也可能保存屏幕。","onboarding.starting":"正在开始…","onboarding.start":"开始","onboarding.error":"无法开始，请稍后重试。",
  "home.shore":"DOONGDOONG海滩","home.write":"写信","home.writingRest":"正在准备下一张信纸和瓶子…","home.heldBottle":"查看捡到的瓶子","home.pickBottle":"捡起水边的瓶子","home.seagull":"听海鸥叫声","home.waiting":"等待新消息…","home.keptCount":"查看已保存的{count}封信","home.guide":"查看使用和安全指南","home.available":"水边有一个可以捡起的瓶子。","home.unavailable":"水边现在没有瓶子。",
  "write.lengthError":"请写10到1,000个字符。","write.blockedPersonal":"瓶中不能包含联系方式、账号或其他可识别个人的信息。","write.blockedCrisis":"这封信目前无法寄出。如果难以独自承受，请立即告诉身边的人或专业人士。","write.blockedSensitive":"请稍微缓和措辞，让所有人都能安心阅读。","write.blockedSpam":"重复或推广内容不能漂向大海。","write.blockedGeneric":"这封信无法寄出，请检查内容。","write.sendError":"无法放出瓶子，请重试。","write.dailyUsed":"今天可寄出的信已经用完。","write.launching":"瓶子正在漂向大海。","write.heading":"写信并装进瓶子","write.crisisHelp":"如果你正面临紧急危险，请立即向身边的人或当地急救服务求助。","write.form":"装进瓶子的信","write.body":"信件内容","write.placeholder":"写给素未谋面的你…","write.today":"今天的日期","write.signature":"署名（选填）","write.sea":"投放的海洋","write.guardrail":"禁止个人信息 · 寄出后无法收回","write.checking":"正在检查信件安全性","write.launch":"把信装进瓶子并放入大海","write.packing":"正在把信装进瓶子。","write.confirmTitle":"要放出这个瓶子吗？","write.confirmDescription":"放出的瓶子无法修改。确定寄出吗？","write.send":"寄出",
  "catch.openError":"无法打开瓶子。","catch.resolveError":"无法处理瓶子。","catch.heading":"打开捡到的瓶子","catch.open":"打开瓶子取出信件","catch.untouched":"不打开，继续漂流","catch.opening":"正在打开瓶子。","catch.received":"收到的信","catch.origin":"来自{country}","catch.translated":"译自{language}","catch.actions":"收到信件的操作","catch.redrift":"再次漂流","catch.keep":"保存","catch.report":"举报","catch.reportConfirm":"确认举报","catch.reportWarning":"举报后，这个瓶子会立即消失。",
  "kept.title":"收藏","kept.description":"保存的瓶子会在30天后消失。","kept.emptyStamp":"空","kept.empty":"身边暂时没有保存的瓶子。","kept.home":"返回海滩","kept.discard":"丢弃","kept.confirm":"确认处理已保存的瓶子","kept.discardWarning":"丢弃后，这封信会立即消失。",
  "time.now":"现在","time.minutes":"{minutes}分钟后","time.hours":"{hours}小时后","time.hoursMinutes":"{hours}小时{minutes}分钟后","time.tomorrow":"明天消失","time.days":"{days}天后消失",
  "guide.eyebrow":"使用指南","guide.title":"DOONGDOONG的约定","guide.oneTitle":"一瓶，一人","guide.oneBody":"读完后再次放出，它会去往下一个人。","guide.blindTitle":"完全匿名","guide.blindBody":"无法知道作者、读者或移动路线。","guide.noReplyTitle":"没有回复的相遇","guide.noReplyBody":"没有回复、点赞或已读回执。","guide.goneTitle":"终会消失","guide.goneBody":"丢弃会立即消失，保存则在30天后消失。","guide.safetyEyebrow":"为了更安全的大海","guide.safetyTitle":"请勿填写任何可识别你的信息。","guide.safety1":"请勿填写真实姓名、电话、邮箱、社交账号、地址或学校。","guide.safety2":"色情、仇恨、威胁、具体犯罪或自伤内容以及广告无法寄出。","guide.safety3":"遇到令人不安或危险的瓶子，可在阅读界面立即举报。","guide.safety4":"技术无法阻止收件人截图等行为。",
  "settings.title":"设置","settings.profileTitle":"国家或地区和语言","settings.profileDescription":"国家或地区决定新瓶子的出发地，语言决定应用界面和翻译。","settings.saveProfile":"保存国家或地区和语言","settings.profileSaved":"已保存国家或地区和语言。","settings.profileError":"无法保存国家或地区和语言。","settings.writingTitle":"写信默认设置","settings.writingDescription":"设置打开新信件时自动填写的内容。","settings.signature":"默认署名","settings.signatureError":"无法保存默认署名。","settings.date":"自动添加今天的日期","settings.motion":"减少动态效果","settings.accountTitle":"账号","settings.accountDescription":"在此设备上退出 DOONGDOONG。","settings.signOut":"退出登录","settings.signingOut":"正在退出…","settings.signOutError":"无法退出登录，请重试。",
  "country.unknown":"未知地点","country.other":"其他国家或地区","sea.pacific":"太平洋","sea.atlantic":"大西洋","sea.indian":"印度洋","sea.arctic":"北冰洋","sea.southern":"南冰洋"
};
